### PR TITLE
SRVLOGIC-202: Schedule apache-main sync from upstream

### PR DESCRIPTION
**Pull request by fantonangeli**
Jira: https://issues.redhat.com/browse/SRVLOGIC-202

Description:
Set up a GitHub Action to sync our midstream main-apache branch with the upstream main branch every day.

Please note:
If approved I will change the default branch to main to let the CI run as scheduled.

Repository used for tests:
https://github.com/fantonangeli/incubator-kie-kogito-images-fantonangeli-test

### CODE REVIEW

**Review by rgdoliveira — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@fantonangeli @rgdoliveira I think we have a problem with the bats tests. Maybe we should investigate more to avoid merging red PRs.

**Comment by rgdoliveira** [comment]
> @fantonangeli @rgdoliveira I think we have a problem with the bats tests. Maybe we should investigate more to avoid merging red PRs.

@ricardozanini  I took a quickly look and it seems it is also failing in Apache upstream PRs with the same error, see https://github.com/apache/incubator-kie-kogito-images/pull/1734 as an example.

IIUC, this test clones ` https://github.com/bats-core/bats-core.git` (master branch?) which may have changed something in the behavior and now the test is failing.

**Comment by rgdoliveira** [comment]
@ricardozanini it seems I fixed it upstream with PR https://github.com/apache/incubator-kie-kogito-images/pull/1738, after it is merged upstream I can sync midstream with upstream.

**Comment by rgdoliveira** [comment]
@ricardozanini @fantonangeli please review https://github.com/kiegroup/kogito-images/pull/10 and after it is merged @fantonangeli can rebase this PR, so hopefully the basts test will be green.

**Comment by rgdoliveira** [comment]
@fantonangeli PR is merged, please rebase your branch in main branch and the bats test should be green.

**Comment by rgdoliveira** [comment]
merged, thanks @fantonangeli

**Pull request merged**
